apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-server-gateway
  namespace: rabbitmq-server-gateway
  labels:
    app: rabbitmq-server-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-server-gateway
  template:
    metadata:
      labels:
        app: rabbitmq-server-gateway
    spec:
      containers:
        - name: rabbitmq-server-gateway
          imagePullPolicy: Always
          image: ionmamaligadev/rabbitmq-server-gateway:0.0.0
          ports:
            - containerPort: 5672
      imagePullSecrets:
        - name: dockerconfigjson
