apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2-rabbitmq-server-gateway-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ionmamaligadev/rabbitmq-server-gateway-cd.git
    targetRevision: HEAD
    path: 2-environments/local/2-rabbitmq-server-gateway-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
